version: '3.8'

services: 
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] 
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=receptify_test
    volumes:
      - ./backend/psql_data:/var/lib/postgresql/data
  server:
    image: receptify-backend-dev
    container_name: receptify-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - SECRET="123456789"
      - PORT=3001
    depends_on:
      - redis
      - postgres
  app:
    image: receptify-frontend-dev
    container_name: receptify-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile 
    volumes:
      - ./frontend/:/usr/src/app 
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server