apiVersion: apps/v1
kind: Deployment
metadata:
  name: receptify-backend-deployment
  labels:
    app: receptify-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receptify-backend
  template:
    metadata:
      labels:
        app: receptify-backend
    spec:
      containers:
      - name: receptify-backend
        image: juhosii/receptify-backend-dev:v1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: postgres-db
        - name: NODE_ENV
          value: development
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: postgres-ip
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url
        - name: REDIS_SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: redis-session
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: receptify-frontend-config
              key: frontend-url
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: email
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: email-password
---
apiVersion: v1
kind: Service
metadata:
  name: receptify-backend-service
spec:
  type: LoadBalancer
  selector:
    app: receptify-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001