name: Publish Images and Deploy to GKE

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install
          cd ..

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Frontend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: frontend
          build-args: |
            "UPLOADCARE_PUBLIC_KEY=${{ secrets.UPLOADCARE_PUBLIC_KEY }}"
          file: frontend/Dockerfile
          push: true
          tags: juhosii/receptify-frontend-dev:${{ github.event.release.tag_name }}

      - name: Build and push Docker image for Backend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: juhosii/receptify-backend-dev:${{ github.event.release.tag_name }}

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials receptify-cluster --zone europe-north1 --project ${{ secrets.GKE_PROJECT }}
          kubectl set image deployment/receptify-backend-deployment receptify-backend=juhosii/receptify-backend-dev:${{ github.event.release.tag_name }}
          kubectl set image deployment/receptify-frontend-deployment receptify-frontend=juhosii/receptify-frontend-dev:${{ github.event.release.tag_name }}

